server:
  port: ${CHAT_SERVICE_PORT}

spring:
  application:
    name: Chat-service

  data:
    mongodb:
      uri: ${MONGO_URI}

  datasource:
    url: ${MYSQL_URI}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PW}

  jpa:
    properties:
      hibernate.default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: ${JPA_AUTO}
    show-sql: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  freemarker:
    cache: false

  jackson:
    serialization:
      fail-on-empty-beans: false


#Eureka
eureka:
  client:
    service-url:
      default_zone: ${EUREKA_URI}

front:
  uri: ${FRONT_URI}

chatroom:
  URI: ${CHATROOM_URI}

# Jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 10000