server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: Member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/open-api/**
        - id: Member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/api/**
          filters:
            - AuthorisationHeaderFilter
        - id: Article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/article-service/open-api/**
        - id: Article-service
          uri: lb://ARTICLE-SERVICE
          predicates:
            - Path=/article-service/api/**
          filters:
            - AuthorisationHeaderFilter
        - id: Chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/api/**
          filters:
            - AuthorisationHeaderFilter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: http://localhost:3000
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#Token
token:
  secret:
    key: ENC(y6vtpjOVBndSN8iIUkHOqaMOSN7/2D5K5HVtyJyaQtCn9Bmq2z4Yr4Gei3i9a9q8TZmPvYunGOo=)
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

# Jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 10000

