server:
  port: ${ARTICLE_SERVICE_PORT}
spring:
  application:
    name: article-service
  datasource:
    url: ${DB_URI}
    username: ${DB_ID}
    password: ${DB_PW}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000

#Eureka
eureka:
  client:
    service-url:
      default_zone: ${EUREKA_URI}

# Jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: ${ALGORITHM}
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 10000