server:
  port: ${ARTICLE_SERVICE_PORT}
spring:
  application:
    name: article-service
  datasource:
    url: ${DB_URI}
    username: ${DB_ID}
    password: ${DB_PW}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
#Eureka
eureka:
  client:
    service-url:
      default_zone: ${EUREKA_URI}
  instance:
    hostname: localhost