server:
  port: 0

spring:
  application:
    name: article-service

  datasource:
    url: jdbc:mysql://coconet.cvmfdihkqonw.ap-southeast-2.rds.amazonaws.com:3306/coconet
    username: admin
    password: coconetadmin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

#Eureka
eureka:
  client:
    service-url:
      default_zone: http://localhost:8761/eureka

